### ISSUE TITLE
Namespace not found in Asp.Net Core project

### ISSUE THREAD

**Issue by diegomodolo** [riganti/dotvvm-contrib#15]
I am new to web development and I am studying dotvvm for one of my company's project. 
I've added the referente to TypeAhead to my project and called the AddContribTypeAheadConfiguration method in my DotvvmStartup class, but the namespace is not found neither during development or runtime.
When I reach the page where I use the control, I get and error message that the namespace was not found.
Am I missing something or the control is not compatible with Asp.Net Core?

**Comment by exyi** [comment]
I think there was a problem when you have multiple dotvvm-contrib
packages installed, due to some name conflict. But it should be fixed
in the latest version, are you sure the NuGet package is up to date?

**Comment by diegomodolo** [comment]
That's my references, do you think that could be the problem?
![image](https://user-images.githubusercontent.com/12273213/35005768-b706ca62-fadb-11e7-8b49-65ebcdf9e88f.png)

**Comment by Leeemons** [comment]
I found problem with assembly name. I will fix this.

**Comment by Leeemons** [comment]
@diegomodolo please download package 1.1.8.1

**Comment by diegomodolo** [comment]
It worked like a charm, thank you!
