### ISSUE TITLE
Event SelectionChanged on Select2 control is generating infinity post calls

### ISSUE THREAD

**Issue by Mitroz** [riganti/dotvvm-contrib#2]

**Comment by tomasherceg** [comment]
Sorry for the delay in response. Can you please provide how you use the control and what type are you trying to data-bind. 
I wasn't able to reproduce it.

**Comment by Mitroz** [comment]
Sorry fo my later response.
Simple example of my usage.
View:
`<dc:Select2 DataSource="{value: Items}" SelectedValues="{value: SelectedItems}" SelectionChanged="{command: ItemSelected()}" style="width: 300px" />`

ViewModel:

```
    public class DefaultViewModel : DotvvmViewModelBase
    {
        public List<string> Items { get; set; }

        public List<string> SelectedItems { get; set; } = new List<string>();


        public DefaultViewModel()
        {

        }

        public override Task PreRender()
        {
            if (!Context.IsPostBack)
            {
                Items = new List<string>() {"string1", "string2", "string3"};
            }

            return base.PreRender();
        }

        public void ItemSelected()
        {            
        }
    }
```

After select any item, calling of method ItemSelected() never end :-]

**Comment by tomasherceg** [comment]
Fixed, sorry that it took so long.
